const DefaultsRoles = [
  {
    name: 'company admin',
    permissions: [
      'List all Bank accounts',
      'Read a specific bank account',
      'Create bank accounts',
      'Update a specific bank account',
      'Delete a specific bank account',
      'Read all clients bank accounts',
      'List all company clients',
      'Read a specific client account',
      'Create client accounts',
      'Update a specific client account',
      'Delete a specific client account',
      'Read number of clients By Company',
      'List all user Companies',
      'Read a specific Company account',
      'Create Company accounts',
      'Update a specific Company account',
      'Delete a specific Company account',
      'Read all admins account in a specific company',
      "Read all user's companies accounts",
      'List all countries',
      'Read a specific country',
      'Create countries',
      'Update a specific country',
      'Delete a specific country',
      'List all company payment plans',
      'Read a specific payment plans',
      'Create payment plans',
      'Update a specific payment plan',
      'Delete a specific payment plan',
      'Read all client payment plans',
      'List all company payments',
      'Read a specific payment',
      'Create payments',
      'Update a specific payment',
      'Delete a specific payment',
      'Read all client payments',
      'List all company roles',
      'Read a specific role',
      'Create roles',
      'Update a specific role',
      'Delete a specific role',
      'Read all permissions',
      'List all company product groups',
      'Read a specific product group',
      'Create product groups',
      'Update a specific product group',
      'Delete a specific product group',
      'Read product product groups',
      'Read project product groups',
      'List all company products',
      'Read a specific product',
      'Create products',
      'Update a specific product',
      'Delete a specific product',
      'List all company project categories',
      'Read a specific project category',
      'Create categories',
      'Update a specific project category',
      'Delete a specific project category',
      'List all company projects',
      'Read a specific project',
      'Create projects',
      'Update a specific project',
      'Delete a specific project',
      'Read all Company projects',
      'Read all company projects',
      'List all company quotes',
      'Read a specific quote',
      'Create quotes',
      'Update a specific quote',
      'Delete a specific quote',
      'Read product quotes',
      'Read sale quotes',
      'List all company sales',
      'Read a specific sale',
      'Create sales',
      'Update a specific sale',
      'Delete a specific sale',
      'Read client sales',
      'List all company users',
      'Read a specific company user',
      'Create company users',
      'Update a specific company user',
      'Delete a specific company user',
    ],
  },
  {
    name: 'basic',
    permissions: [
      'List all Bank accounts',
      'Read a specific bank account',
      'Read all clients bank accounts',
      'List all company clients',
      'Read a specific client account',
      'Read number of clients By Company',
      'List all user Companies',
      'Read a specific Company account',
      'Read all admins account in a specific company',
      "Read all user's companies accounts",
      'List all countries',
      'Read a specific country',
      'List all company payment plans',
      'Read a specific payment plans',
      'Read all client payment plans',
      'List all company payments',
      'Read a specific payment',
      'Read all client payments',
      'List all company roles',
      'Read a specific role',
      'Read all permissions',
      'List all company product groups',
      'Read a specific product group',
      'Read product product groups',
      'Read project product groups',
      'List all company products',
      'Read a specific product',
      'List all company project categories',
      'Read a specific project category',
      'List all company projects',
      'Read a specific project',
      'Read all Company projects',
      'Read all company projects',
      'List all company quotes',
      'Read a specific quote',
      'Read product quotes',
      'Read sale quotes',
      'List all company sales',
      'Read a specific sale',
      'Read client sales',
      'List all company users',
      'Read a specific company user',
    ],
  },
  {
    name: 'project admin',
    permissions: [
      'List all Bank accounts',
      'Read a specific bank account',
      'Create bank accounts',
      'Update a specific bank account',
      'Delete a specific bank account',
      'Read all clients bank accounts',
      'List all company clients',
      'Read a specific client account',
      'Create client accounts',
      'Update a specific client account',
      'Delete a specific client account',
      'Read number of clients By Company',
      'List all user Companies',
      'Read a specific Company account',
      'Create Company accounts',
      'Update a specific Company account',
      'Delete a specific Company account',
      'Read all admins account in a specific company',
      "Read all user's companies accounts",
      'List all countries',
      'Read a specific country',
      'Create countries',
      'Update a specific country',
      'Delete a specific country',
      'List all company payment plans',
      'Read a specific payment plans',
      'Create payment plans',
      'Update a specific payment plan',
      'Delete a specific payment plan',
      'Read all client payment plans',
      'List all company payments',
      'Read a specific payment',
      'Create payments',
      'Update a specific payment',
      'Delete a specific payment',
      'Read all client payments',
      'Read all permissions',
      'List all company product groups',
      'Read a specific product group',
      'Create product groups',
      'Update a specific product group',
      'Delete a specific product group',
      'Read product product groups',
      'Read project product groups',
      'List all company products',
      'Read a specific product',
      'Create products',
      'Update a specific product',
      'Delete a specific product',
      'List all company project categories',
      'Read a specific project category',
      'Create categories',
      'Update a specific project category',
      'Delete a specific project category',
      'List all company projects',
      'Read a specific project',
      'Create projects',
      'Update a specific project',
      'Delete a specific project',
      'Read all Company projects',
      'Read all company projects',
      'List all company quotes',
      'Read a specific quote',
      'Create quotes',
      'Update a specific quote',
      'Delete a specific quote',
      'Read product quotes',
      'Read sale quotes',
      'List all company sales',
      'Read a specific sale',
      'Create sales',
      'Update a specific sale',
      'Delete a specific sale',
      'Read client sales',
      'List all company users',
      'Read a specific company user',
    ],
  },
];

const ROLES = {
  'company admin': {
    name: 'company admin',
    permissions: [
      'List all Bank accounts',
      'Read a specific bank account',
      'Create bank accounts',
      'Update a specific bank account',
      'Delete a specific bank account',
      'Read all clients bank accounts',
      'List all company clients',
      'Read a specific client account',
      'Create client accounts',
      'Update a specific client account',
      'Delete a specific client account',
      'Read number of clients By Company',
      'List all user Companies',
      'Read a specific Company account',
      'Create Company accounts',
      'Update a specific Company account',
      'Delete a specific Company account',
      'Read all admins account in a specific company',
      "Read all user's companies accounts",
      'List all countries',
      'Read a specific country',
      'Create countries',
      'Update a specific country',
      'Delete a specific country',
      'List all company payment plans',
      'Read a specific payment plans',
      'Create payment plans',
      'Update a specific payment plan',
      'Delete a specific payment plan',
      'Read all client payment plans',
      'List all company payments',
      'Read a specific payment',
      'Create payments',
      'Update a specific payment',
      'Delete a specific payment',
      'Read all client payments',
      'List all company roles',
      'Read a specific role',
      'Create roles',
      'Update a specific role',
      'Delete a specific role',
      'Read all permissions',
      'List all company product groups',
      'Read a specific product group',
      'Create product groups',
      'Update a specific product group',
      'Delete a specific product group',
      'Read product product groups',
      'Read project product groups',
      'List all company products',
      'Read a specific product',
      'Create products',
      'Update a specific product',
      'Delete a specific product',
      'List all company project categories',
      'Read a specific project category',
      'Create categories',
      'Update a specific project category',
      'Delete a specific project category',
      'List all company projects',
      'Read a specific project',
      'Create projects',
      'Update a specific project',
      'Delete a specific project',
      'Read all Company projects',
      'Read all company projects',
      'List all company quotes',
      'Read a specific quote',
      'Create quotes',
      'Update a specific quote',
      'Delete a specific quote',
      'Read product quotes',
      'Read sale quotes',
      'List all company sales',
      'Read a specific sale',
      'Create sales',
      'Update a specific sale',
      'Delete a specific sale',
      'Read client sales',
      'List all company users',
      'Read a specific company user',
      'Create company users',
      'Update a specific company user',
      'Delete a specific company user',
    ],
  },
};

export const getRolePermissions = (name: string): Array<string> => {
  const role = (ROLES as any)[name];
  return role ? role.permissions : [];
};

export default DefaultsRoles;
